### ISSUE TITLE
Imported asset was very large?

### ISSUE THREAD

**Issue by scolar** [gdamoreira/google-ar-asset-converter#1]
my issue is as follow：
![image](https://user-images.githubusercontent.com/11267256/41596015-6f5ca4e0-73fb-11e8-9e50-476abc0be208.png)

**Comment by gdamoreira** [comment]
Hi, this issue apparently is caused by wrong use of the material.
These binaries were extracted from google-ar plugin, so this is an issue that need to be addressed to their repo:
https://github.com/google-ar/sceneform-android-sdk 

Hope I have helped somehow.
