### ISSUE TITLE
sfb file is too big for our models, around 10MB

### ISSUE THREAD

**Issue by CranberryYam** [gdamoreira/google-ar-asset-converter#10]
For other files of one model, the total size is 4 MB. However, the sfb file of this model is around 10MB. Do we really need sfb file? Our app downloads the model in realtime, so we really concern about the size of models.

**Comment by gdamoreira** [comment]
Hi @CranberryYam, this question must be redirected to google's sceneform repo. https://github.com/google-ar/sceneform-android-sdk/issues

**Comment by CranberryYam** [comment]
No problem. Do you have any idea what's the best 3D model for ARCore?

**Comment by gdamoreira** [comment]
You can use SFB files or glTF.
