### ISSUE TITLE
Getting below error while running the convertor script

### ISSUE THREAD

**Issue by smvinoth** [gdamoreira/google-ar-asset-converter#11]
command used:
./sceneform_sdk/linux/converter -a -d --mat ./sceneform_sdk/default_materials/obj_material.sfm --outdir ./output/ ./input/andy.obj

Error message:

./sceneform_sdk/linux/converter: /lib64/libc.so.6: version `GLIBC_2.10' not found (required by ./sceneform_sdk/linux/converter)
./sceneform_sdk/linux/converter: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./sceneform_sdk/linux/converter)
./sceneform_sdk/linux/converter: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by ./sceneform_sdk/linux/converter)
./sceneform_sdk/linux/converter: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by ./sceneform_sdk/linux/converter)
./sceneform_sdk/linux/converter: /lib64/libc.so.6: version `GLIBC_2.6' not found (required by ./sceneform_sdk/linux/converter)
./sceneform_sdk/linux/converter: /lib64/libc.so.6: version `GLIBC_2.12' not found (required by ./sceneform_sdk/linux/converter)

**Comment by gdamoreira** [comment]
Hi @smvinoth maybe this thread helps you https://askubuntu.com/questions/421642/libc-so-6-version-glibc-2-14-not-found

Try this solution and tell me your feedback.
