### ISSUE TITLE
Getting error file converting files from POLY

### ISSUE THREAD

**Issue by smvinoth** [gdamoreira/google-ar-asset-converter#12]
Getting below resource not found error, when I try to convert file from Poly to .sfb format.
Image is generated but colors are not rendered properly.

ubuntu@ubuntu:~/Downloads/google-ar-asset-converter-master$ ./sceneform_sdk/linux/converter -a -d --mat ./sceneform_sdk/default_materials/obj_material.sfm --outdir ./output/ ./input/human_male.obj
Warning: Imported asset was very large (683.8 x 1763.7 x 398.2 m)
         Setting scale to: 0.0025113 to compensate
Info: Generated SFA from ./input/human_male.obj
> WARNING: 20 textures declared in source assets were not found on disk:
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Body_Opacity.png
> - man1_Body_Normal_Normal_Bump.tga
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Body_Specular.png
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Body_Diffuse.png
> - man1_Bottom_Normal_Normal_Bump.tga
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Bottom_Specular.png
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Bottom_Opacity.png
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Bottom_Diffuse.png
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Top_Opacity.png
> - man1_Top_Normal_Normal_Bump.tga
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Top_Specular.png
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Top_Diffuse.png
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Shoes_Opacity.png
> - man1_Shoes_Normal_Normal_Bump.tga
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Shoes_Specular.png
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Shoes_Diffuse.png
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Hair_Opacity.png
> - man1_Hair_Normal_Normal_Bump.tga
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Hair_Specular.png
> - D:\VirtualSpeech\App\Unity\VS_google_cardboard_v31\Assets\avatars\male_high_res\man1.fbm\man1_Hair_Diffuse.png
> (use -I to add other search folders)
Info: Wrote SFA (json) to ./output/human_male.sfa (2555 bytes)
Info: Wrote SFB to ./output/human_male.sfb (1393752 bytes)

**Comment by smvinoth** [comment]
I am downloading the .Obj from Google poly

https://poly.google.com/view/2vBYKsnu2HX

**Comment by gdamoreira** [comment]
Hi, did you tried converting using the official Sceneform Gradle Plugin ? This error looks like some texture is missing. Maybe the .mtl is referring some folder that don't exists in your environment. Try opening, and changing the paths before submiting a ticket in google-ar sceneform repo.

Let me know if worked.
