### ISSUE TITLE
E/Filament: Panic

### ISSUE THREAD

**Issue by ramunl** [gdamoreira/google-ar-asset-converter#18]
If I convert fbx to sfb and try to use it with com.google.ar.sceneform:animation:1.10.0 my app crashes with:
 E/Filament: Panic
    in filament::Material *filament::Material::Builder::build(filament::Engine &):86
    reason: Material version mismatch. Expected 3 but received 2.
2019-06-25 16:05:31.929 27367-27367/com.google.ar.sceneform.samples.hellosceneform A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 27367 (.hellosceneform), pid 27367 (.hellosceneform)

Could you update it to 1.10.0 version to make it work with com.google.ar.sceneform:animation:1.10.0 ?

**Comment by gdamoreira** [comment]
Hi @ramunl,

sorry for not responding this issue soon. I'm going to update the plugin version now.

Best regards.
