### ISSUE TITLE
abstracting sceneform_sdk files

### ISSUE THREAD

**Issue by mahlm** [gdamoreira/google-ar-asset-converter#2]
I'm curious how the sceneform_sdk files get abstracted from the sdk, could you provide some insight on how this is done?

Thanks!

**Comment by gdamoreira** [comment]
Hi,

there are no abstraction on sceneform binaries. I just found that the gradle plugins works calling these binaries files to generate the SFA and SFB files.

I extracted these binaries from the official sceneform plugin jar.

I used this link to download the jar file:
https://mvnrepository.com/artifact/com.google.ar.sceneform/plugin/1.3.0

Hope I was clear.

:)

**Comment by mahlm** [comment]
Very helpful and clear, thank you!!
