### ISSUE TITLE
Fbx to sfb file conversion doesn't work

### ISSUE THREAD

**Issue by razamerchantwork** [gdamoreira/google-ar-asset-converter#20]
Hi I am trying to convert a fbx file by this command 

./converter -a -d --mat /Users/macbookpro/Downloads/google-ar-asset-converter-master/sceneform_sdk/default_materials/fbx_material.sfm --outdir /Users/macbookpro/Downloads/google-ar-asset-converter-master/output  /Users/macbookpro/Downloads/Display8.fbx 

 but I am getting below Error

2019-09-20 12:53:05.577 converter[576:11382] FATAL (null)
2019-09-20 12:53:05.579 converter[576:11382] FATAL Dumping stack:
#00 pc 0000000104f9a510 /Users/macbookpro/Downloads/google-ar-asset-converter-master/sceneform_sdk/mac/./converter (ion::base::logging_internal::Logger::~Logger()+128)
#01 pc 0000000104f6b33f /Users/macbookpro/Downloads/google-ar-asset-converter-master/sceneform_sdk/mac/./converter (lull::tool::CompactBoneIndex(int)+266)
#02 pc 0000000104f6b981 /Users/macbookpro/Downloads/google-ar-asset-converter-master/sceneform_sdk/mac/./converter (lull::tool::GatherBoneIndexMaps(std::__1::vector<lull::tool::Bone, std::__1::allocator<lull::tool::Bone> > const&, std::__1::vector<lull::tool::Vertex, std::__1::allocator<lull::tool::Vertex> > const&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >*)+379)
#03 pc 0000000104f5b42c /Users/macbookpro/Downloads/google-ar-asset-converter-master/sceneform_sdk/mac/./converter (lull::tool::ExportModelInstance(lull::tool::Model const&, lull::ModelInstanceDefT*, lull::ModelPipelineRenderableDefT*, lull::tool::ExportOptions)+134)
#04 pc 0000000104f5fcde /Users/macbookpro/Downloads/google-ar-asset-converter-master/sceneform_sdk/mac/./converter (lull::tool::ExportModel(std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, lull::tool::Model, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, lull::tool::Model> > > const&, std::__1::unordered_map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, lull::tool::TextureInfo, std::__1::hash<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::equal_to<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, lull::tool::TextureInfo> > > const&, lull::tool::ExportOptions, lull::ModelPipelineDefT*)+924)
#05 pc 0000000104f54af3 /Users/macbookpro/Downloads/google-ar-asset-converter-master/sceneform_sdk/mac/./converter (lull::tool::ModelPipeline::Build(lull::tool::ExportOptions)+47)
#06 pc 0000000104f52d00 /Users/macbookpro/Downloads/google-ar-asset-converter-master/sceneform_sdk/mac/./converter (lull::tool::ModelPipeline::Import(lull::ModelPipelineDef const*, lull::tool::ExportOptions)+7296)
#07 pc 000000010446d2e0 /Users/macbookpro/Downloads/google-ar-asset-converter-master/sceneform_sdk/mac/./converter (sceneform::converter::Converter::Run()+5876)
#08 pc 000000010446af94 /Users/macbookpro/Downloads/google-ar-asset-converter-master/sceneform_sdk/mac/./converter (main+3924)

is there something wrong with the command

**Comment by gdamoreira** [comment]
Hi @razamerchantwork, have you tried converting this .fbx file using the plugin in Android Studio?

It seems that is a problem with the converter itself. In this case you should redirect your issue to Google Sceneform repo.
