### ISSUE TITLE
Error: Running matc: Failed to run external command

### ISSUE THREAD

**Issue by eimermusic** [gdamoreira/google-ar-asset-converter#21]
I got one (pretty large) example OBJ file which is causing the error in the title when I run it server-side on AWS (Linux). The same conversion does succeed locally on Mac OS though.

`Error: Running matc: Failed to run external command`

Has anyone seen this error?
Can anyone help point me in the right direction?

I am not sure what to make of it. My other test files work fine and the only notable difference is the size of the input file.

- Does not seem to reach a memory limit, as far as AWS metrics can show me.
- It is finding the `matc` command (removing that executable gives a different error).
- The error is returned in STDOut not STDErr.

Note: I am posting here in the hope that someone else also using this converter separately might have seen the same error output.

**Comment by gdamoreira** [comment]
Hi @eimermusic, have you tried the conversion directly from Android Studio?

These binaries are extracted from there, so if you are facing some problem with them, you should open a ticket support on official repository.

https://github.com/google-ar/sceneform-android-sdk
