### ISSUE TITLE
Incosistency in results of Sceneform plugin

### ISSUE THREAD

**Issue by terezo** [gdamoreira/google-ar-asset-converter#3]
Hi, 

I am getting different results in comparison to current version of Sceneform v1.3.0.
There are more details in this issue: https://github.com/google-ar/sceneform-android-sdk/issues/150.
Fortunately your scripts are giving a better results, except of shadow, but I think it should not be different from results you get from plugin.

**Comment by gdamoreira** [comment]
Hi @terezo, I am looking to your .sfa assets, and found that maybe you could be using wrong plugin version on your android project.

Looking to your files, I see that the sfa file generated from sceneform plugin has these properties:
`suggested_collision: {
         center: {
            x: 0,
            y: 0,
            z: 0,
         },
         size: {
            x: 1,
            y: 1,
            z: 1,
         },
         type: "Box",
      },`

But, if you compare the version 1.0.1 and 1.3.0, that attribute don't exists anymore. This attribute was replaced by:

`collision: {},`

Please, verify your gradle configuration.

**Comment by terezo** [comment]
@necrostylery thanks, it kept wrong gradle dependency, though I reinstall plugin to latest version from AS `Settings`
