### ISSUE TITLE
Error: Textures declared in source assets were not found on disk

### ISSUE THREAD

**Issue by 0v3rt1r3d** [gdamoreira/google-ar-asset-converter#4]
Hello! I try convert a model from `.fbx` format to `.sfb`. The model contains links to textures, and when I try to convert it I got:

Command to converter: 
```./converter -a -d --mat ../default_materials/fbx_material.sfm ~/correct_path_to_fbx/sun.fbx```

Output from converter:
```
WARNING: 2 textures declared in source assets were not found on disk:
> - Tex\Sun01_A.png
> - Tex\Sun02_A.png
```
The directory `~/correct_path_to_fbx` contains `Tex\Sun01_A.png` and `Tex\Sun02_A.png`

Actually, I got sfb-file, but it doesn't include textures.

What am I doing wrong?

**Comment by 0v3rt1r3d** [comment]
Also, I try to use gradle-plugin `com.google.ar.sceneform.plugin` for converting, but I have the same problem running gradle-task

**Comment by gdamoreira** [comment]
This issue must be redirected to sceneform repo (https://github.com/google-ar/sceneform-android-sdk). This is a bug from sceneform converter.

As an alternative try converting using a FBX with embedded textures, here where I work we export all our FBX files with embedded textures and the conversion works nice.

**Comment by 0v3rt1r3d** [comment]
Thank you!
