### ISSUE TITLE
Changing textures at runtime

### ISSUE THREAD

**Issue by Popeyef5** [gdamoreira/google-ar-asset-converter#5]
Hi, thanks for this, it really helped with my app. However, I am having issues with changing the texture of sfb renderables converted from obj by this converter. Have you had to do so? If so, how did you accomplish it? renderable.material.setTexture appears to do nothing at all. All I have to do is change the color. Thanks!

**Comment by gdamoreira** [comment]
Hi @Popeyef5, in my work we don't change the textures in runtime, so I'm not familiar with this issue. But it seems that it is a bug from sceneform API. That must be reported in the correct repo (https://github.com/google-ar/sceneform-android-sdk).

Sorry if I couldn't help you. But these binaries are extracted from the sceneform gradle plugin jar file, so the problem must be in sceneform asset converter.
