### ISSUE TITLE
Update to Sceneform 1.4.0

### ISSUE THREAD

**Issue by ManuelTS** [gdamoreira/google-ar-asset-converter#6]
https://plugins.jetbrains.com/plugin/10698-google-sceneform-tools-beta-

**Comment by gdamoreira** [comment]
Hi @ManuelTS the plugin you are referring is only on AndroidStudio, the binaries this plugin uses is sceneform plugin 1.3.0.

There are no 1.4.0 yet in the main repo (https://mvnrepository.com/artifact/com.google.ar.sceneform/plugin).

When the new 1.4.0 sceneform plugin jar file is launched, I will update this repo.

**Comment by gdamoreira** [comment]
Hi @ManuelTS, the version 1.4.0 is launched! So I updated the binaries in this repo. Please try again and tell me if everything is OK.
