### ISSUE TITLE
How to use this converter in android device in runtime?

### ISSUE THREAD

**Issue by nekitr** [gdamoreira/google-ar-asset-converter#8]
Hi, i want to use this converter on an Android device, for runtime converting .obj to .sfb.
My code does not work.

val root = getExternalFilesDir(null).toString() + "/google-ar-asset-converter" 

val command = "chmod u+x $root/sceneform_sdk/linux/converter  -a -d --mat $root/sceneform_sdk/default_materials/obj_material.sfm --outdir $root/output/ $root/input/andy.obj"

val process: Process = Runtime.getRuntime().exec("$command")

E/ERROR: chmod: -a: No such file or directory
chmod: -d: No such file or directory
chmod: --mat: No such file or directory
chmod: --outdir: No such file or directory

Do you have any idea how to fix this error?

**Comment by gdamoreira** [comment]
Hi @GopNick7, I never tried using this converter in Android environment. But, your code are trying to do chmod in converter and using at same time.

Try typing 2 commands, one for chmod command and other for the converter command.

**Comment by nekitr** [comment]
Thank you for answer, i will be trying
