### ISSUE TITLE
SFA file content is not used to update SFB file

### ISSUE THREAD

**Issue by wegherfe** [gdamoreira/google-ar-asset-converter#9]
I would expect that, if an SFA file is present for the given SFB and if converter is launched without -a option, the content of SFA is used to update SFB.

Android Studio allows changing SFA file and to update SFB. How can I achieve the same result using converter script?

The reason why I am asking this question is the following: converter script, as well as Android Studio, detects the object as too large and so sets the scale to some (random) value to compensate. I need to set the scale to 100%. In Android Studio, I am used to edit generated SFA files, change the scale to what I need and then rebuild.

**Comment by AlexKriatov** [comment]
Android Studio uses the gradle plugin to determine if the sfa file exists, and different commands are used depending on it. 
You can use following commands to make sfb file from sfa like in android studio plugin:
`converter <PATH_TO_SFA>(.sfa file) --desktop --output <OUTPUT_PATH>`

**Comment by gdamoreira** [comment]
Hi @wegherfe, I usually don't change my .sfa files. But probably the @AlexKriatov answer is correct. Try and give us your feedback.

**Comment by wegherfe** [comment]
It works perfectly. I would add some explanation in usage (shown by -h) to explain that sfa can be a input file as well.
Thank you very much.
